{  
      "schedule":[  
         {  
            "key":"7503041-4",
            "times":{  
               "arrival":{  
                  "scheduled":"08:43:38",
                  "estimated":"2016-08-08T08:43:38"
               },
               "departure":{  
                  "scheduled":"08:43:38",
                  "estimated":"2016-08-08T08:43:38"
               }
            },
            "variant":{  
               "key":"68-1-W",
               "name":"to University of Winnipeg"
            },
            "bus":{  
               "bike-rack":"false",
               "easy-access":"true"
            }
         },
         {  
            "key":"7503042-4",
            "times":{  
               "arrival":{  
                  "scheduled":"09:08:38",
                  "estimated":"2016-08-08T09:08:38"
               },
               "departure":{  
                  "scheduled":"09:08:38",
                  "estimated":"2016-08-08T09:08:38"
               }
            },
            "variant":{  
               "key":"68-1-W",
               "name":"to University of Winnipeg"
            },
            "bus":{  
               "bike-rack":"false",
               "easy-access":"true"
            }
         },
         {  
            "key":"7503043-4",
            "times":{  
               "arrival":{  
                  "scheduled":"09:31:38",
                  "estimated":"2016-08-08T09:31:38"
               },
               "departure":{  
                  "scheduled":"09:31:38",
                  "estimated":"2016-08-08T09:31:38"
               }
            },
            "variant":{  
               "key":"68-1-W",
               "name":"to University of Winnipeg"
            },
            "bus":{  
               "bike-rack":"false",
               "easy-access":"true"
            }
         },
         {  
            "key":"7503056-4",
            "times":{  
               "arrival":{  
                  "scheduled":"09:59:38",
                  "estimated":"2016-08-08T09:59:38"
               },
               "departure":{  
                  "scheduled":"09:59:38",
                  "estimated":"2016-08-08T09:59:38"
               }
            },
            "variant":{  
               "key":"68-1-W",
               "name":"to University of Winnipeg"
            },
            "bus":{  
               "bike-rack":"false",
               "easy-access":"true"
            }
         }
      ]
   }